### ISSUE TITLE
draw_model_execute hook crashing

### ISSUE THREAD

**Issue by codecheck01** [lstrsrt/csgo_internal_base#2]

**Comment by lstrsrt** [comment]
Works for me. What line are you crashing on? If you're not playing on insecure, it might also be related to Valve's return address checks.

**Comment by lstrsrt** [comment]
Call stack says it's crashing in set_flag, so there is a high likelihood that something is wrong with either the material pointer or the function definition. Try returning an existing material in init_material (comment out the first line).
