### ISSUE TITLE
Setting up the CSGO Internal Base

### ISSUE THREAD

**Issue by pvpb0t** [lstrsrt/csgo_internal_base#9]
Hey there! I was curious if you could help me set up the csgo_internal_base cheat. I'm completely new to this and I just wanted to try it out for fun. Can you provide a step-by-step guide on how to set it up? Also, what are the basic requirements for using this cheat? I would really appreciate your help! 🙏🕹️

**Comment by lstrsrt** [comment]
1. Install Visual Studio Community with the "Desktop development with C++" module
2. Download the repo
3. Open the .sln file
4. Build

No requirements other than having CSGO and the Visual Studio C++ compiler installed.
